<?php
if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly
?>
<input type="hidden" name="bo_customer_review_watson_active_settings_tab" value="help"/>

<h2 style="padding-top: 1em;"><?php _e('HELP', 'bo-customer-review-watson'); ?></h2>
<p><?php  $env = bo_customer_review_watson_environment_variables();
    _e('You are currently in Version', 'bo-customer-review-watson'); echo " ".$env->version; ?></p>
<p><?php _e('For more help, go to our site, or ask to the support', 'bo-customer-review-watson'); ?>
<br><a href="https://wc-reviews-watson-tone-analyzer.blue-origami-digital.com/help" target="_blank"><?php _e('HELP', 'bo-customer-review-watson'); ?>/</a>
    <br><a href="https://wc-reviews-watson-tone-analyzer.blue-origami-digital.com/support" target="_blank"><?php _e('Support request by email basic on our site', 'bo-customer-review-watson'); ?></a>
    <br><?php _e('And Support tickets on Wordpress.org on the repository page of this plugin', 'bo-customer-review-watson'); ?>n.</a>
</p>
<p><?php _e('This plugin is built by', 'bo-customer-review-watson'); ?> <a href="https://blue-origami-digital.com/">Blue Origami Digital, France</a> </p>


<h4>1/ <?php _e('HOW TO UPDATE MY PLUGIN FREE VERSION TO A NEW VERSION?', 'bo-customer-review-watson'); ?></h4>

<p><?php _e('It could happend, in some cases, with the Free version licence, that the free license could be not well activated or blocked, you could be blocked to get an access to the plugin update. In this case:<br>1. It should be possible to go to wp-admin/admin.php?page=bo-customer-review-watson-account and do "sync" licence,.<br>2. If not working, you can redownload again the last version and upload it again. Don\'t worry no data will be lost.<br> 3. If not possible in your case, the best to do is to contact us and we will generated a new licence remotely and it should be possible to sync the licence,  or try "Activate licence" with the one we will send to you.', 'bo-customer-review-watson'); ?></p>
<p><?php _e('Note that we are working on it, to see how to simplify the Update process for free versions. Contact us for any issues.', 'bo-customer-review-watson'); ?></p>

<h4>2/ <?php _e('How to create my account at IBM Watson', 'bo-customer-review-watson'); ?></h4>

<p><?php _e('You will need to have a free account at Watson, and create a "Tone Analyzer" service. This is free up to 2500 calls to the API / month', 'bo-customer-review-watson'); ?></p>
<p><?php _e('Then you will receive connexion informations, and you just need to insert your information in this plugin', 'bo-customer-review-watson'); ?>.
<p>> <?php _e('Create your free acount at Watson:', 'bo-customer-review-watson'); ?>
    <a target="_blank" href="https://cloud.ibm.com/registration?target=%2Fcatalog%2Fservices%2Ftone-analyzer%3FhideTours%3Dtrue%26?cm_sp=WatsonPlatform-WatsonPlatform-_-OnPageNavCTA-IBMWatson_ToneAnalyzer-_-Watson_Developer_Website">Create my Account</a>
</p>


<h4>3/ <?php _e('How to create a Service for Tone Analyzer, in your account', 'bo-customer-review-watson'); ?></h4>
<p>> <?php _e('Once your account is created, create your tone analyser service:', 'bo-customer-review-watson'); ?>
    <a target="_blank" href="https://cloud.ibm.com/registration?target=%2Fcatalog%2Fservices%2Ftone-analyzer%3FhideTours%3Dtrue%26?cm_sp=WatsonPlatform-WatsonPlatform-_-OnPageNavCTA-IBMWatson_ToneAnalyzer-_-Watson_Developer_Website"><?php _e('Create my Service', 'bo-customer-review-watson'); ?></a>
</p>
<p><?php _e('WARNING: note that here you need to select the SERVER LOCATION, please save this information, you will need to define the server target', 'bo-customer-review-watson'); ?></p>
<img class="boai_imgborder" src="<?php echo BODAI_URL ?>/admin/images/createServiceWatson.JPG">


<h4>4/ <?php _e('How to find my API Key or Username/Password, in the Service', 'bo-customer-review-watson'); ?></h4>
<p>> <?php _e('After creation of your service, you will be redirected to the service dashboard', 'bo-customer-review-watson'); ?>.</p>
<img class="boai_imgborder" src="<?php echo BODAI_URL ?>/admin/images/dashboardServiceWatson.JPG">
<p>><?php _e('Then find the <strong>MANAGE page</strong>', 'bo-customer-review-watson'); ?></p>
<p><?php _e('You will find here the IDENTIFICATION INFORMATION for your service, API connection values', 'bo-customer-review-watson'); ?>.
    <br><?php _e('DEPENDING on your ACCOUNT TYPE, there is TWO TYPEs of values, an API KEY, or a USERNAME + PASSWORD', 'bo-customer-review-watson'); ?>
</p>
<p><?php _e('Find here the <strong>API KEY or USERNAME + PASSWORD</strong>, note it', 'bo-customer-review-watson'); ?>,
    <br><?php _e('and an URL. This URL will be automatically generated by the plugin, you just need to know what is the SERVER LOCATION city you selected on previous step (example here:', 'bo-customer-review-watson'); ?> gateway-lon = london)
</p>
<img class="boai_imgborder" src="<?php echo BODAI_URL ?>/admin/images/WatsonGetIndentification.JPG">


<h4>5/ <?php _e('What is my account type?', 'bo-customer-review-watson'); ?></h4>
<p><?php _e('DEPENDING on your ACCOUNT TYPE, there is TWO TYPEs of values, an API KEY, or a USERNAME + PASSWORD', 'bo-customer-review-watson'); ?></p>
<p><?php _e('Go to your Watson Tone Analyser service and find the page "Manage" or "Identification informations", where you should find a block with an API KEY, or in other cases (less often), a USERNAME + PASSWORD', 'bo-customer-review-watson'); ?></p>
<p><?php _e('More globally if your account is recent, it should be an API KEY', 'bo-customer-review-watson'); ?></p>


<h4>6/ <?php _e('Find you IBM Watson Server Endpoint server?', 'bo-customer-review-watson'); ?></h4>
<p><?php _e('When you created your service, you had to select a city location for this service', 'bo-customer-review-watson'); ?>.</p>
<p><?php _e('But you can also find it following the initial part of your service Url, given at the same place than your API Key information', 'bo-customer-review-watson'); ?></p>
<p><?php _e('The server\'s location list is the following:', 'bo-customer-review-watson'); ?></p>

    <li>Dallas: https://<strong>gateway</strong>.watsonplatform.net/tone-analyzer/api</li>
    <li>Washington DC: https://<strong>gateway-wdc</strong>.watsonplatform.net/tone-analyzer/api</li>
    <li>Frankfurt: https://<strong>gateway-fra</strong>.watsonplatform.net/tone-analyzer/api</li>
    <li>Sydney: https://<strong>gateway-syd</strong>.watsonplatform.net/tone-analyzer/api</li>
    <li>Tokyo: https://<strong>gateway-tok</strong>.watsonplatform.net/tone-analyzer/api</li>
    <li>London: https://<strong>gateway-lon</strong>.watsonplatform.net/tone-analyzer/api</li>


